#!/usr/bin/env ruby

require "cgi"
require "fileutils"

fail "Missing or incorrect 'AOC_SESSION' env variable" if ENV["AOC_SESSION"]&.size != 128

now = Time.now.localtime("-05:00")
day = ARGV.size > 0 ? ARGV[0].to_i : now.day
year = ARGV.size > 1 ? ARGV[1].to_i : now.year

fail "It's not that time of the year yet" unless (year < now.year || now.month == 12) && (1..25) === day

def get(path)
  `curl -sS -H 'Cookie: session=#{ENV["AOC_SESSION"]}' 'https://adventofcode.com#{path}'`
end

puts "Retrieving problem name..."

html_name = get("/#{year}/day/#{day}")[/<h2>--- Day \d+: (.+) ---<\/h2>/, 1]

name = CGI.unescapeHTML(html_name)
        .gsub(/[^\w-]+/i, "_")
        .gsub(/_{2,}/, "_")
        .gsub(/^_+|_+$/, "")
        .downcase

FileUtils.mkdir_p year.to_s

filename = "%d/%02d_%s.rb" % [year, day, name]

if File.exist?(filename)
  print "Do you want to overwrite '#{filename}'? [Y/n] "
  exit if STDIN.gets[/n/i]
end

puts "Downloading input..."

input = get("/#{year}/day/#{day}/input")

puts "Creating '#{filename}'..."

code = <<~CODE


__END__
#{input.chomp}
CODE

IO.write(filename, code)

puts "Done!"
